### ISSUE TITLE
Implementation of Beatmaps View

### ISSUE THREAD

**Issue by Founntain** [Founntain/osuplayer#209]
## Beatmaps View Implementation

We want to implement the Beatmaps View from the stats-webpage. We are unable to attach a screenshot as the stats-webpage is currently down due to the new API.

The Beatmaps View consists of a list of played beatmaps, ordered by the total number of times they have been played. Each entry in the list includes the following information:

- Artist and Title: The name of the artist and the title of the beatmap.
- Total Plays: The overall number of times the beatmap has been played.
- Most Active User: The user who has played the beatmap the most, along with their username and the count of plays.
- Beatmap Page Link: A hyperlink to the beatmap page on the osu! website.

### To-Do:
- [x] Implement all necessary API changes.
- [x] Implement the basic view.
- [x] Load the data and display it.
- [x] Refactor the code.
